import type {
  DiffAction,
  DiffItem,
  DiffPath,
  HelmGuardReport,
  NormalizationResult,
  ReportConfig,
  ReportNormalizationSummary,
  ReportSchema,
  ReportSelection,
  ReportSummary,
  ResourceIdentifier,
  ResourceResult,
  ResourceStatus,
} from "../../../shared/report-contract";

export type {
  DiffAction,
  DiffItem,
  DiffPath,
  HelmGuardReport,
  NormalizationResult,
  ReportConfig,
  ReportNormalizationSummary,
  ReportSchema,
  ReportSelection,
  ReportSummary,
  ResourceIdentifier,
  ResourceResult,
  ResourceStatus,
};
